name: Compile Common Lisp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Compile Common Lisp Program Cross-Platform
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install sbcl -y
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --no-sysinit --no-userinit --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))' --quit
        
    - name: Install dependencies on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install sbcl
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --no-sysinit --no-userinit --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))' --quit
        
    - name: Install dependencies on Windows
      if: matrix.os == 'windows-2019'
      run: | 
        choco install sbcl
        curl -O https://beta.quicklisp.org/quicklisp.lisp
        sbcl --no-sysinit --no-userinit --load quicklisp.lisp --eval '(quicklisp-quickstart:install)' --eval '(ql-util:without-prompting (ql:add-to-init-file))' --quit
       
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile Common Lisp program with SBCL #Chicken Scheme on non-Windows
      #if: matrix.os != 'windows-2019'
      #run: sbcl --non-interactive --eval '(require :asdf)' --eval '(push \#p\"${{ github.workspace }}\" asdf:*central-registry*)' --eval "(asdf:compile-system :example-system)"
      run: sbcl --non-interactive --eval '(require :asdf)' --eval '(push "${{ github.workspace }}/" asdf:*central-registry*)' --eval "(asdf:compile-system :example-system)"

   # - name: Compile Scheme Program with Chicken Scheme on Windows
   #   if: matrix.os == 'windows-2019'
   #   run: C:\tools\chicken\bin\csc -static main.scm 
