name: Compile Common Lisp
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Compile Common Lisp Program Cross-Platform
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]

    steps:
    - uses: actions/checkout@v3

    - name: Install Common Lisp on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install sbcl -y

    - name: Install Common Lisp on macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install sbcl

    - name: Install Common Lisp on Windows
      if: matrix.os == 'windows-2019'
      run: |
        choco install sbcl

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Quicklisp, compile Common Lisp program with SBCL
      #if: matrix.os != 'windows-2019'
      #run: sbcl --non-interactive --eval '(require :asdf)' --eval '(push \#p\"${{ github.workspace }}\" asdf:*central-registry*)' --eval "(asdf:compile-system :example-system)"
      run: sbcl --non-interactive --load configure-and-compile.lisp

   # - name: Compile Scheme Program with Chicken Scheme on Windows
   #   if: matrix.os == 'windows-2019'
   #   run: C:\tools\chicken\bin\csc -static main.scm
