#TODO

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    name: Release Common Lisp program cross-platform
    uses: ./.github/workflows/compile.yml # heavy lifting here
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]


    steps:
# should be done in compile.yml, fingers crossed
#    - uses: actions/checkout@v3

    - name: Create release executable with Common Lisp
      if: matrix.os != 'windows-2019'
      run: sbcl --eval "(progn (setq uiop:*image-entry-point* #'main) (uiop:dump-image \"hello\" :executable t)"
      
    - name: Compile Scheme Program with Chicken Scheme on Windows
      if: matrix.os == 'windows-2019'
      run: C:\tools\chicken\bin\csc -static main.scm 

    - name: Upload executable for Windows
      if: matrix.os == 'windows-2019'
      uses: actions/upload-artifact@v3
      with:
        name: compiled-program-${{ matrix.os }}
        path: main.exe
    
    - name: Upload executable for non-Windows
      if: matrix.os != 'windows-2019'
      uses: actions/upload-artifact@v3
      with:
        name: compiled-program-${{ matrix.os }}
        path: main
 
